`ifndef ASCII_UART_SENSOR_PIPELINE_DEFS_VH
`define ASCII_UART_SENSOR_PIPELINE_DEFS_VH

`define AUSP_CTX_W 2
`define AUSP_CTX_WATCH 2'd0
`define AUSP_CTX_STOPWATCH 2'd1
`define AUSP_CTX_SR04 2'd2
`define AUSP_CTX_DHT11 2'd3

`define AUSP_SRC_W 2
`define AUSP_SRC_LOCAL 2'd0
`define AUSP_SRC_REMOTE 2'd1
`define AUSP_SRC_SYSTEM 2'd2

`define AUSP_CMD_W 4
`define AUSP_CMD_NONE 4'd0
`define AUSP_CMD_BTNR 4'd1
`define AUSP_CMD_BTNR_HOLD 4'd2
`define AUSP_CMD_BTNL 4'd3
`define AUSP_CMD_BTNU 4'd4
`define AUSP_CMD_BTND 4'd5
`define AUSP_CMD_SNAP 4'd6
`define AUSP_CMD_CLR 4'd7

`define AUSP_EVT_W 4
`define AUSP_EVT_NONE 4'd0
`define AUSP_EVT_BTNR_SHORT 4'd1
`define AUSP_EVT_BTNR_HOLD 4'd2
`define AUSP_EVT_BTNL_SHORT 4'd3
`define AUSP_EVT_BTNU_SHORT 4'd4
`define AUSP_EVT_BTND_SHORT 4'd5
`define AUSP_EVT_SNAP 4'd6
`define AUSP_EVT_CLR 4'd7

`define AUSP_ACT_W 4
`define AUSP_ACT_NONE 4'd0
`define AUSP_ACT_DISPLAY_TOGGLE 4'd1
`define AUSP_ACT_WATCH_SET_TOGGLE 4'd2
`define AUSP_ACT_WATCH_EDIT 4'd3
`define AUSP_ACT_STOPWATCH_RUNSTOP 4'd4
`define AUSP_ACT_STOPWATCH_CLEAR 4'd5
`define AUSP_ACT_STOPWATCH_DIRECTION 4'd6
`define AUSP_ACT_SNAPSHOT 4'd7
`define AUSP_ACT_SOFT_RESET 4'd8

`endif
